FROM node:22-alpine
RUN apk add --no-cache openjdk21-jre
RUN npm install -g firebase-tools
WORKDIR /app
COPY firebase.json .
COPY database.rules.json .
EXPOSE 9000
CMD ["firebase", "emulators:start", "--project", "demo-test"]
