export const words = [
  "Banane", "Chien", "Chat", "Maison", "Voiture", "Arbre", "Soleil", "Lune", "Etoile", "Livre",
  "Pomme", "Ordinateur", "Telephone", "Fleur", "Oiseau", "Poisson", "Montagne", "Bateau", "Avion", "Train",
  "Velo", "Chaussure", "Chapeau", "Lunettes", "Montre", "Crayon", "Stylo", "Gomme", "Ciseaux", "Papier",
  "Couteau", "Fourchette", "Cuillere", "Assiette", "Verre", "Tasse", "Bouteille", "Lit", "Table", "Chaise",
  "Canapé", "Television", "Porte", "Fenetre", "Clé", "Sac", "Valise", "Parapluie", "Manteau", "Pantalon",
  "Chemise", "Robe", "Jupe", "Chaussette", "Gant", "Echarpe", "Bonnet", "Casquette", "Bague", "Collier",
  "Bracelet", "Boucle d'oreille", "Brosse", "Peigne", "Miroir", "Savon", "Shampoing", "Dentifrice", "Brosse a dents", "Serviette",
  "Nuage", "Pluie", "Neige", "Vent", "Eclair", "Tonnerre", "Arc-en-ciel", "Glace", "Feu", "Eau",
  "Terre", "Sable", "Roche", "Herbe", "Feuille", "Racine", "Branche", "Tronc", "Foret", "Desert",
  "Guitare", "Piano", "Trompette", "Tambour", "Violon", "Flute", "Microphone", "Casque", "Haut-parleur", "Radio",
  "Ampoule", "Bougie", "Lampe", "Lanterne", "Pinceau", "Peinture", "Toile", "Chevalet", "Appareil photo", "Caméra",
  "Lentille", "Jumelles", "Telescope", "Microscope", "Boussole", "Carte", "Globe", "Valise", "Passeport", "Billet",
  "Clef", "Cadenas", "Serrure", "Tiroir", "Placard", "Armoire", "Etagere", "Bureau", "Fauteuil", "Tapis",
  "Rideau", "Couverture", "Oreiller", "Matelas", "Drap", "Serviette", "Peignoir", "Baignoire", "Douche", "Lavabo",
  "Toilettes", "Poubelle", "Balai", "Serpilliere", "Aspirateur", "Eponge", "Sceau", "Tuyau", "Arrosoir", "Tondeuse",
  "Rateau", "Pelle", "Brouette", "Marteau", "Clou", "Vis", "Tournevis", "Scie", "Pince", "Cle a molette",
  "Perceuse", "Pinceau", "Rouleau", "Echelle", "Brique", "Ciment", "Tuile", "Planche", "Corde", "Fil",
  "Aiguille", "Bouton", "Fermeture eclair", "Tissu", "Coton", "Laine", "Soie", "Cuir", "Plastique", "Verre",
  "Metal", "Bois", "Carton", "Papier", "Livre", "Cahier", "Classeur", "Dossier", "Enveloppe", "Timbre",
  "Lettre", "Carte", "Affiche", "Journal", "Magazine", "Bande dessinee", "Dictionnaire", "Atlas", "Calendrier", "Horloge",
  "Reveil", "Chronomètre", "Thermomètre", "Balance", "Mètre", "Règle", "Compas", "Equerre", "Rapporteur", "Calculatrice",
  "Ordinateur portable", "Tablette", "Clavier", "Souris", "Ecran", "Imprimante", "Scanner", "Routeur", "Disque dur", "Clé USB",
  "Cable", "Prise", "Interrupteur", "Batterie", "Pile", "Chargeur", "Ecouteurs", "Manette", "Console", "Jeu",
  "Dé", "Pion", "Plateau", "Carte", "Puzzle", "Poupée", "Peluche", "Balle", "Ballon", "Raquette",
  "Filet", "But", "Panier", "Gant", "Casque", "Protège-tibias", "Sifflet", "Chronomètre", "Podium", "Médaille",
  "Coupe", "Trophée", "Drapeau", "Bannière", "Ecusson", "Logo", "Affiche", "Panneau", "Feu de signalisation", "Passage piéton",
  "Trottoir", "Route", "Autoroute", "Pont", "Tunnel", "Rond-point", "Carrefour", "Passage a niveau", "Gare", "Aéroport",
  "Port", "Station", "Arret", "Billet", "Carte", "Abonnement", "Ticket", "Valise", "Sac", "Bagage",
  "Voiture", "Camion", "Bus", "Moto", "Vélo", "Trotinette", "Skateboard", "Roller", "Bateau", "Navire",
  "Sous-marin", "Avion", "Hélicoptère", "Fusée", "Satellite", "Station spatiale", "Tracteur", "Moissonneuse", "Pelleteuse", "Grue",
  "Ambulance", "Camion de pompier", "Voiture de police", "Taxi", "Fourgon", "Charrette", "Traineau", "Calèche", "Poussette", "Fauteuil roulant",
  "Béquille", "Plâtre", "Pansement", "Seringue", "Stéthoscope", "Thermomètre", "Pilule", "Gélule", "Sirop", "Ordonnance",
  "Recette", "Menu", "Carte", "Addition", "Pourboire", "Caisse", "Tiroir", "Monnaie", "Billet", "Pièce",
  "Cheque", "Carte bancaire", "Portefeuille", "Porte-monnaie", "Tirelire", "Coffre", "Banque", "Distributeur", "Guichet", "Bourse",
  "Pomme", "Poire", "Banane", "Orange", "Citron", "Fraise", "Framboise", "Cerise", "Raisin", "Pêche",
  "Abricot", "Prune", "Melon", "Pastèque", "Kiwi", "Ananas", "Mangue", "Papaye", "Goyave", "Noix de coco"
];

export function getRandomWord(): string {
  return words[Math.floor(Math.random() * words.length)];
}
