export const words = [
  "Banane", "Chien", "Chat", "Maison", "Voiture", "Arbre", "Soleil", "Lune", "Étoile", "Livre",
  "Pomme", "Ordinateur", "Téléphone", "Fleur", "Oiseau", "Poisson", "Montagne", "Bateau", "Avion", "Train",
  "Vélo", "Chaussure", "Chapeau", "Lunettes", "Montre", "Crayon", "Stylo", "Gomme", "Ciseaux", "Papier",
  "Couteau", "Fourchette", "Cuillère", "Assiette", "Verre", "Tasse", "Bouteille", "Lit", "Table", "Chaise",
  "Canapé", "Télévision", "Porte", "Fenêtre", "Clé", "Sac", "Valise", "Parapluie", "Manteau", "Pantalon",
  "Chemise", "Robe", "Jupe", "Chaussette", "Gant", "Écharpe", "Bonnet", "Casquette", "Bague", "Collier",
  "Bracelet", "Boucle d'oreille", "Brosse", "Peigne", "Miroir", "Savon", "Shampoing", "Dentifrice", "Brosse à dents", "Serviette",
  "Nuage", "Pluie", "Neige", "Vent", "Éclair", "Tonnerre", "Arc-en-ciel", "Glace", "Feu", "Eau",
  "Terre", "Sable", "Roche", "Herbe", "Feuille", "Racine", "Branche", "Tronc", "Forêt", "Désert",
  "Guitare", "Piano", "Trompette", "Tambour", "Violon", "Flûte", "Microphone", "Casque", "Haut-parleur", "Radio",
  "Ampoule", "Bougie", "Lampe", "Lanterne", "Pinceau", "Peinture", "Toile", "Chevalet", "Appareil photo", "Caméra",
  "Lentille", "Jumelles", "Télescope", "Microscope", "Boussole", "Carte", "Globe", "Passeport", "Billet",
  "Clef", "Cadenas", "Serrure", "Tiroir", "Placard", "Armoire", "Étagère", "Bureau", "Fauteuil", "Tapis",
  "Rideau", "Couverture", "Oreiller", "Matelas", "Drap", "Peignoir", "Baignoire", "Douche", "Lavabo",
  "Toilettes", "Poubelle", "Balai", "Aspirateur", "Éponge", "Seau", "Tuyau", "Arrosoir", "Tondeuse",
  "Râteau", "Pelle", "Brouette", "Marteau", "Clou", "Vis", "Tournevis", "Scie", "Pince", "Clé à molette",
  "Perceuse", "Rouleau", "Échelle", "Brique", "Ciment", "Tuile", "Planche", "Corde", "Fil",
  "Aiguille", "Bouton", "Fermeture éclair", "Tissu", "Coton", "Laine", "Soie", "Cuir", "Plastique",
  "Métal", "Bois", "Carton", "Cahier", "Classeur", "Dossier", "Enveloppe", "Timbre",
  "Lettre", "Affiche", "Journal", "Magazine", "Bande dessinée", "Dictionnaire", "Atlas", "Calendrier", "Horloge",
  "Réveil", "Chronomètre", "Thermomètre", "Balance", "Mètre", "Règle", "Compas", "Équerre", "Rapporteur", "Calculatrice",
  "Ordinateur portable", "Tablette", "Clavier", "Souris", "Écran", "Imprimante", "Scanner", "Routeur", "Clé USB",
  "Câble", "Prise", "Interrupteur", "Batterie", "Pile", "Chargeur", "Écouteurs", "Manette", "Console", "Jeu",
  "Dé", "Pion", "Plateau", "Puzzle", "Poupée", "Peluche", "Balle", "Ballon", "Raquette",
  "Filet", "But", "Panier", "Sifflet", "Podium", "Médaille",
  "Coupe", "Trophée", "Drapeau", "Bannière", "Écusson", "Panneau", "Feu de signalisation", "Passage piéton",
  "Trottoir", "Route", "Autoroute", "Pont", "Tunnel", "Rond-point", "Carrefour", "Passage à niveau", "Gare", "Aéroport",
  "Port", "Station", "Arrêt", "Abonnement", "Ticket", "Bagage",
  "Camion", "Bus", "Moto", "Trottinette", "Skateboard", "Roller", "Navire",
  "Sous-marin", "Hélicoptère", "Fusée", "Satellite", "Station spatiale", "Tracteur", "Moissonneuse", "Pelleteuse", "Grue",
  "Ambulance", "Camion de pompier", "Voiture de police", "Taxi", "Fourgon", "Charrette", "Traîneau", "Calèche", "Poussette", "Fauteuil roulant",
  "Béquille", "Plâtre", "Pansement", "Seringue", "Stéthoscope", "Pilule", "Gélule", "Sirop",
  "Menu", "Addition", "Pièce",
  "Chèque", "Carte bancaire", "Portefeuille", "Porte-monnaie", "Tirelire", "Coffre", "Banque", "Distributeur",
  "Poire", "Orange", "Citron", "Fraise", "Framboise", "Cerise", "Raisin", "Pêche",
  "Melon", "Pastèque", "Ananas", "Noix de coco"
];

export function getRandomWord(): string {
  return words[Math.floor(Math.random() * words.length)];
}
