export const words = [
  "Banane", "Chien", "Chat", "Maison", "Voiture", "Arbre", "Soleil", "Lune", "Étoile", "Livre",
  "Pomme", "Ordinateur", "Téléphone", "Fleur", "Oiseau", "Poisson", "Montagne", "Bateau", "Avion", "Train",
  "Vélo", "Chaussure", "Chapeau", "Lunettes", "Montre", "Crayon", "Stylo", "Gomme", "Ciseaux", "Papier",
  "Couteau", "Fourchette", "Cuillère", "Assiette", "Verre", "Tasse", "Bouteille", "Lit", "Table", "Chaise",
  "Canapé", "Télévision", "Porte", "Fenêtre", "Clé", "Sac", "Valise", "Parapluie", "Manteau", "Pantalon",
  "Chemise", "Robe", "Jupe", "Chaussette", "Gant", "Écharpe", "Bonnet", "Casquette", "Bague", "Collier",
  "Bracelet", "Boucle d'oreille", "Brosse", "Peigne", "Miroir", "Savon", "Shampoing", "Dentifrice", "Brosse à dents", "Serviette",
  "Nuage", "Pluie", "Neige", "Vent", "Éclair", "Tonnerre", "Arc-en-ciel", "Glace", "Feu", "Eau",
  "Terre", "Sable", "Roche", "Herbe", "Feuille", "Racine", "Branche", "Tronc", "Forêt", "Désert",
  "Guitare", "Piano", "Trompette", "Tambour", "Violon", "Flûte", "Microphone", "Casque", "Haut-parleur", "Radio",
  "Ampoule", "Bougie", "Lampe", "Lanterne", "Pinceau", "Peinture", "Toile", "Chevalet", "Appareil photo", "Caméra",
  "Lentille", "Jumelles", "Télescope", "Microscope", "Boussole", "Carte", "Globe", "Passeport", "Billet", "Clef",
  "Cadenas", "Serrure", "Tiroir", "Placard", "Armoire", "Étagère", "Bureau", "Fauteuil", "Tapis", "Rideau",
  "Couverture", "Oreiller", "Matelas", "Drap", "Peignoir", "Baignoire", "Douche", "Lavabo", "Toilettes", "Poubelle",
  "Balai", "Aspirateur", "Éponge", "Seau", "Tuyau", "Arrosoir", "Tondeuse", "Râteau", "Pelle", "Brouette",
  "Marteau", "Clou", "Vis", "Tournevis", "Scie", "Pince", "Clé à molette", "Perceuse", "Rouleau", "Échelle",
  "Brique", "Ciment", "Tuile", "Planche", "Corde", "Fil", "Aiguille", "Bouton", "Fermeture éclair", "Tissu",
  "Coton", "Laine", "Soie", "Cuir", "Plastique", "Métal", "Bois", "Carton", "Cahier", "Classeur",
  "Dossier", "Enveloppe", "Timbre", "Lettre", "Affiche", "Journal", "Magazine", "Bande dessinée", "Dictionnaire", "Atlas",
  "Calendrier", "Horloge", "Réveil", "Chronomètre", "Thermomètre", "Balance", "Mètre", "Règle", "Compas", "Équerre",
  "Rapporteur", "Calculatrice", "Ordinateur portable", "Tablette", "Clavier", "Souris", "Écran", "Imprimante", "Scanner", "Routeur",
  "Clé USB", "Câble", "Prise", "Interrupteur", "Batterie", "Pile", "Chargeur", "Écouteurs", "Manette", "Console",
  "Jeu", "Dé", "Pion", "Plateau", "Puzzle", "Poupée", "Peluche", "Balle", "Ballon", "Raquette",
  "Filet", "But", "Panier", "Sifflet", "Podium", "Médaille", "Coupe", "Trophée", "Drapeau", "Bannière",
  "Écusson", "Panneau", "Feu de signalisation", "Passage piéton", "Trottoir", "Route", "Autoroute", "Pont", "Tunnel", "Rond-point",
  "Carrefour", "Passage à niveau", "Gare", "Aéroport", "Port", "Station", "Arrêt", "Abonnement", "Ticket", "Bagage",
  "Camion", "Bus", "Moto", "Trottinette", "Skateboard", "Roller", "Navire", "Sous-marin", "Hélicoptère", "Fusée",
  "Satellite", "Station spatiale", "Tracteur", "Moissonneuse", "Pelleteuse", "Grue", "Ambulance", "Camion de pompier", "Voiture de police", "Taxi",
  "Fourgon", "Charrette", "Traîneau", "Calèche", "Poussette", "Fauteuil roulant", "Béquille", "Plâtre", "Pansement", "Seringue",
  "Stéthoscope", "Pilule", "Gélule", "Sirop", "Menu", "Addition", "Pièce", "Chèque", "Carte bancaire", "Portefeuille",
  "Porte-monnaie", "Tirelire", "Coffre", "Banque", "Distributeur", "Poire", "Orange", "Citron", "Fraise", "Framboise",
  "Cerise", "Raisin", "Pêche", "Melon", "Pastèque", "Ananas", "Noix de coco", "Cœur", "Triangle", "Carré",
  "Cercle", "Flèche", "Croix", "Spirale", "Vague", "Infini", "Dollar", "Euro", "Dièse", "Trèfle",
  "Diamant", "Couronne", "Ancre", "Cible", "Sourire", "Triste", "Fantôme", "Tombe", "Cadeau", "Sapin",
  "Œuf", "Fromage", "Pain", "Pizza", "Frites", "Burger", "Hot-dog", "Sandwich", "Croissant", "Sucette",
  "Bonbon", "Donut", "Cookie", "Sushi", "Soupe", "Gâteau", "Tarte", "Miel", "Chocolat", "Lait",
  "Café", "Thé", "Sel", "Poivre", "Jus", "Canette", "Taco", "Burrito", "Crêpe", "Gaufre",
  "Popcorn", "Carotte", "Tomate", "Champignon", "Poireau", "Radis", "Piment", "Avocat", "Olive", "Patate",
  "Oignon", "Kiwi", "Abricot", "Prune", "Figue", "Aubergine", "Courgette", "Concombre", "Poivron", "Ail",
  "Serpent", "Escargot", "Tortue", "Requin", "Baleine", "Dauphin", "Poulpe", "Méduse", "Étoile de mer", "Crabe",
  "Crevette", "Papillon", "Coccinelle", "Araignée", "Vers", "Chenille", "Limace", "Grenouille", "Canard", "Pingouin",
  "Hibou", "Lapin", "Cochon", "Girafe", "Éléphant", "Mouton", "Vache", "Lion", "Ours", "Singe",
  "Chauve-souris", "Kangourou", "Koala", "Panda", "Zèbre", "Tigre", "Renard", "Loup", "Cerf", "Écureuil",
  "Castor", "Hérisson", "Taupe", "Rat", "Hamster", "Poule", "Coq", "Poussin", "Oie", "Cygne",
  "Corbeau", "Aigle", "Perroquet", "Toucan", "Flamant", "Colibri", "Autruche", "Cadre", "Allumette", "Briquet",
  "Cendrier", "Ceinture", "Cravate", "Nœud", "Masque", "Canne", "Éventail", "Baguette", "Cube", "Sphère",
  "Cylindre", "Pyramide", "Tornade", "Volcan", "Île", "Palmier", "Cactus", "Lotus", "Rose", "Tulipe",
  "Trésor", "Cloche", "Bouclier", "Épée", "Hache", "Arc", "Plume", "Encre", "Parchemin", "Loupe",
  "Sablier", "Crâne", "Os", "Canon", "Hamac", "Cabane", "Tente", "Gourde", "Phare", "Bouée",
  "Surf", "Parasol", "Théière", "Thermos", "Vase", "Pot", "Bouilloire", "Grille-pain", "Tipi", "Igloo",
  "Château", "Puits", "Bassin", "Fontaine", "Graine", "Champ", "Ferme", "Moulin", "Grange", "Barrière",
  "Épouvantail", "Nid", "Aile", "Patte", "Queue", "Griffe", "Corne", "Sabot", "Naseau", "Moustache",
  "Barbe", "Cheveux", "Oeil", "Bouche", "Nez", "Oreille", "Dent", "Langue", "Main", "Pied",
  "Doigt", "Bras", "Jambe", "Ventre", "Dos", "Cerveau", "Poumon", "Estomac", "Muscle", "Sang",
  "Larme", "Sueur", "Salive", "Poing", "Pouce", "Salut", "Chut", "Prière", "Temple",
  "Église", "Mosquée", "Synagogue", "Pharaon", "Sphinx", "Sarcophage", "Oasis", "Dune", "Dromadaire", "Plante",
  "Arbuste", "Bananier", "Pommier", "Oranger", "Pêcher", "Cerisier", "Vigne", "Grappe", "Lierre", "Mousse",
  "Fougère", "Pelouse", "Foin", "Paille", "Blé", "Maïs", "Grain", "Farine", "Spaghetti", "Nouilles",
  "Ramen", "Maki", "Wasabi", "Soja", "Sauce", "Vinaigre", "Huile", "Beurre", "Crème", "Yaourt",
  "Flan", "Pudding", "Confiture", "Marmelade", "Compote", "Soda", "Cola", "Limonade", "Grenadine",
  "Menthe", "Expresso", "Cappuccino", "Milkshake", "Cocktail", "Glaçon", "Muffin", "Cupcake", "Macaron", "Gaufrette",
  "Biscotte", "Tartine", "Chips", "Cacahuète", "Pistache", "Noisette", "Amande"
];

export function getRandomWord(): string {
  return words[Math.floor(Math.random() * words.length)];
}
